### ISSUE TITLE
Track progress of each project

### ISSUE THREAD

**Issue by chinesedfan** [Bogdanp/awesome-advent-of-code#56]
Maybe a little hard. But I doubt every added project can reach 50 stars at last. Without tracking, this repository will become a list like Github search results. Not awesome.

**Comment by Bogdanp** [comment]
If you're suggesting that we should track how far each project got, then that's a great idea. I look forward to your PR.

**Comment by chinesedfan** [comment]
Yes, just a suggestion. But why don't you close this issue so quickly? Shall we wait until someone finish it? It makes nobody else except you and me know this thing.

**Comment by hughjdavey** [comment]
This would be cool but I can't see how it could be done... obviously we have the repository links for each project but there is no way I can think of to check how far they got without doing some horrible grep for e.g. "Day 3" and then assuming they solved it cos there's a reference to it somewhere in the source. The only other way is to do something like tell everyone to add their max day in their README so we can check it, but this relies on honesty and on people bothering to do it. @chinesedfan any ideas?

**Comment by chinesedfan** [comment]
@hughjdavey A simple way is to check the last update time. Believe me. More than half of them will stop updating before Christmas. If we want to be more accurate, designing a format is a good method, i.e. 3/25 or 19/50. If not introducing too much trouble, we can also ask authors to provide a CI test script and output that rate. There is not an 100% safe way I think.

**Comment by hughjdavey** [comment]
@chinesedfan Good idea to check the last update time - that will be 99% accurate and is by far the easiest. Next problem is how to update it in the README - I know GitHub has those "build passing" badges that clearly update themselves so maybe we can use those APIs and spin up e.g. a free heroku instance to periodically check repository last update times?

**Comment by hughjdavey** [comment]
[This site](https://shields.io/#/) seems to do what we want... scroll down to "Dynamic Badges" and you can see they accept a url to return data

**Comment by chinesedfan** [comment]
Check this badge. I love it. If @Bogdanp agrees with me, I can send a PR.

![GitHub last commit](https://img.shields.io/github/last-commit/chinesedfan/adventofcode.svg)

**Comment by hughjdavey** [comment]
Oh that's great is that built into GitHub?

**Comment by Bogdanp** [comment]
> Check this badge. I love it. If @Bogdanp agrees with me, I can send a PR.

@chinesedfan please do!

**Comment by chinesedfan** [comment]
@hughjdavey I think yes. Adding them once without any prices to maintain.

**Comment by AlexAegis** [comment]
How about multi-year repositories? Or people who participate later? The last commit is good to see if something is actively developed or not, but not for progress. The most straightforward solution as mentioned before would be to allow for PR's about updating progress. But, it does have the cost of having to merge a lot of requests.

I have a far better solution that requires no maintenance other than solvers updating their own repositories:

Shields.io provides a [service](https://shields.io/endpoint ) where you can feed it a JSON endpoint with a certain schema that will show you a custom badge. And guess what, we can use `raw.githubusercontent.com` as an API for this. 

When pointing to a nonexistent endpoint it looks ugly ( [![2018 Progress](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/AlexAegis/advent-of-code/master/.github/badges/nonexistent)](./src/2018/)
 ) so I'd only add it using PR's, but one PR is still far better than any solutions before and can be added with the initial one if we let the contributor know about it.


## Proof of concept:

[![2018 Progress](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/AlexAegis/advent-of-code/master/.github/badges/2018.json)](./src/2018/)

The way I'd do it is (as seen as the previous example) is by placing a badges folder in a "hidden" folder (I'd use the existing `.github` folder, but a `.aoc` or a straight-up `.shields` or `.badges` folder, without an inner `badges` would be good too) and placing a `<year>.json` file inside which would then contain the response to render the badge:

```json
{
	"schemaVersion": 1,
	"label": "AoC 2018",
	"message": "14/25",
	"color": "orange"
}
```

I'd reserve `"color": "green"` for completed repos.

This way everybody could just update their progress inside their repositories so there's no need for any PR's except the initial one.

Ps.:

This solution would require some **discipline** though but I think in this community we can count on that. Especially because we only have to care about a niche sub-community of the ones who'd like to show their work. An additional disclaimer in the `readme.md` would be nice too, something on the line of "We do not take responsibility for the content of custom badges".
